/**
 * Cancer catalogue — GENERATED, do not edit by hand.
 *
 * Source: "Cancer Type Drop Down.xlsx" supplied for the challenge demonstration.
 * SHA-256: e92d6fdb1ad150ff3d887cdd4aff972556c8164f874a62d40cf762e3fa182b2d
 * Regenerate: node scripts/import-workbooks.mjs <cancer.xlsx> <net.xlsx>
 *
 * This is the supplied demonstration catalogue, NOT an exhaustive or medically
 * validated ontology of every cancer subtype. Entries carry curated aliases and
 * conflicts only where a wrong match would be clinically dangerous; the rest
 * fall back to their workbook label.
 */

export interface CancerEntry {
  /** Stable slug used in storage, the API and WebMCP. */
  id: string;
  /** What the person sees. */
  label: string;
  /** The workbook's original wording, preserved for provenance. */
  sourceLabel: string;
  /** Sent to ClinicalTrials.gov as query.cond. */
  query: string;
  /** Accepted alternative wordings, for search and condition matching. */
  aliases: string[];
  /**
   * Wordings that must never satisfy this entry even though they contain its
   * words — "non-small cell lung cancer" must not match "small cell lung cancer".
   */
  conflicts: string[];
  /** Set where the display label narrows a broader workbook category. */
  sourceCategory?: string;
}

export const CANCERS: readonly CancerEntry[] = [
  {
    id: "acute-lymphoblastic-leukemia",
    label: "Acute Lymphoblastic Leukemia",
    sourceLabel: "Acute Lymphoblastic Leukemia",
    query: "acute lymphoblastic leukemia",
    aliases: ["acute lymphoblastic leukemia", "acute lymphoblastic leukaemia", "acute lymphocytic leukemia", "ALL"],
    conflicts: ["chronic lymphocytic leukemia", "CLL", "small lymphocytic lymphoma"],
  },
  {
    id: "acute-myeloid-leukemia",
    label: "Acute Myeloid Leukemia",
    sourceLabel: "Acute Myeloid Leukemia",
    query: "acute myeloid leukemia",
    aliases: ["acute myeloid leukemia", "acute myeloid leukaemia", "acute myelogenous leukemia", "AML"],
    conflicts: ["chronic myeloid leukemia", "chronic myelogenous leukemia", "CML"],
  },
  {
    id: "ampullary-adenocarcinoma",
    label: "Ampullary Adenocarcinoma",
    sourceLabel: "Ampullary Adenocarcinoma",
    query: "Ampullary Adenocarcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "anal-carcinoma",
    label: "Anal Carcinoma",
    sourceLabel: "Anal Carcinoma",
    query: "Anal Carcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "appendiceal-neoplasms-and-cancers",
    label: "Appendiceal Neoplasms and Cancers",
    sourceLabel: "Appendiceal Neoplasms and Cancers",
    query: "Appendiceal Neoplasms and Cancers",
    aliases: [],
    conflicts: [],
  },
  {
    id: "basal-cell-skin-cancer",
    label: "Basal Cell Skin Cancer",
    sourceLabel: "Basal Cell Skin Cancer",
    query: "Basal Cell Skin Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "b-cell-lymphomas",
    label: "B-Cell Lymphomas",
    sourceLabel: "B-Cell Lymphomas",
    query: "B-Cell Lymphomas",
    aliases: [],
    conflicts: [],
  },
  {
    id: "biliary-tract-cancers",
    label: "Biliary Tract Cancers",
    sourceLabel: "Biliary Tract Cancers",
    query: "Biliary Tract Cancers",
    aliases: [],
    conflicts: [],
  },
  {
    id: "bladder-cancer",
    label: "Bladder Cancer",
    sourceLabel: "Bladder Cancer",
    query: "Bladder Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "bone-cancer",
    label: "Bone Cancer",
    sourceLabel: "Bone Cancer",
    query: "Bone Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "breast-cancer",
    label: "Breast Cancer",
    sourceLabel: "Breast Cancer",
    query: "breast cancer",
    aliases: ["breast cancer", "breast carcinoma", "breast neoplasm", "carcinoma of the breast"],
    conflicts: [],
  },
  {
    id: "castleman-disease",
    label: "Castleman Disease",
    sourceLabel: "Castleman Disease",
    query: "Castleman Disease",
    aliases: [],
    conflicts: [],
  },
  {
    id: "central-nervous-system-cancers",
    label: "Central Nervous System Cancers",
    sourceLabel: "Central Nervous System Cancers",
    query: "Central Nervous System Cancers",
    aliases: [],
    conflicts: [],
  },
  {
    id: "cervical-cancer",
    label: "Cervical Cancer",
    sourceLabel: "Cervical Cancer",
    query: "Cervical Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "chronic-lymphocytic-leukemia-small-lymphocytic-lymphoma",
    label: "Chronic Lymphocytic Leukemia / Small Lymphocytic Lymphoma",
    sourceLabel: "Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma",
    query: "chronic lymphocytic leukemia",
    aliases: ["chronic lymphocytic leukemia", "chronic lymphocytic leukaemia", "small lymphocytic lymphoma", "CLL", "SLL"],
    conflicts: ["acute lymphoblastic leukemia", "acute lymphocytic leukemia"],
  },
  {
    id: "chronic-myeloid-leukemia",
    label: "Chronic Myeloid Leukemia",
    sourceLabel: "Chronic Myeloid Leukemia",
    query: "chronic myeloid leukemia",
    aliases: ["chronic myeloid leukemia", "chronic myeloid leukaemia", "chronic myelogenous leukemia", "CML"],
    conflicts: ["acute myeloid leukemia", "acute myelogenous leukemia", "AML"],
  },
  {
    id: "colon-cancer",
    label: "Colon Cancer",
    sourceLabel: "Colon Cancer",
    query: "Colon Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "cutaneous-lymphomas",
    label: "Cutaneous Lymphomas",
    sourceLabel: "Cutaneous Lymphomas",
    query: "Cutaneous Lymphomas",
    aliases: [],
    conflicts: [],
  },
  {
    id: "dermatofibrosarcoma-protuberans",
    label: "Dermatofibrosarcoma Protuberans",
    sourceLabel: "Dermatofibrosarcoma Protuberans",
    query: "Dermatofibrosarcoma Protuberans",
    aliases: [],
    conflicts: [],
  },
  {
    id: "esophageal-and-esophagogastric-junction-cancers",
    label: "Esophageal and Esophagogastric Junction Cancers",
    sourceLabel: "Esophageal and Esophagogastric Junction Cancers",
    query: "Esophageal and Esophagogastric Junction Cancers",
    aliases: [],
    conflicts: [],
  },
  {
    id: "gastric-cancer",
    label: "Gastric Cancer",
    sourceLabel: "Gastric Cancer",
    query: "Gastric Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "gastrointestinal-stromal-tumors",
    label: "Gastrointestinal Stromal Tumors",
    sourceLabel: "Gastrointestinal Stromal Tumors",
    query: "Gastrointestinal Stromal Tumors",
    aliases: [],
    conflicts: [],
  },
  {
    id: "gestational-trophoblastic-neoplasia",
    label: "Gestational Trophoblastic Neoplasia",
    sourceLabel: "Gestational Trophoblastic Neoplasia",
    query: "Gestational Trophoblastic Neoplasia",
    aliases: [],
    conflicts: [],
  },
  {
    id: "hairy-cell-leukemia",
    label: "Hairy Cell Leukemia",
    sourceLabel: "Hairy Cell Leukemia",
    query: "Hairy Cell Leukemia",
    aliases: [],
    conflicts: [],
  },
  {
    id: "head-and-neck-cancers",
    label: "Head and Neck Cancers",
    sourceLabel: "Head and Neck Cancers",
    query: "Head and Neck Cancers",
    aliases: [],
    conflicts: [],
  },
  {
    id: "hepatocellular-carcinoma",
    label: "Hepatocellular Carcinoma",
    sourceLabel: "Hepatocellular Carcinoma",
    query: "Hepatocellular Carcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "histiocytic-neoplasms",
    label: "Histiocytic Neoplasms",
    sourceLabel: "Histiocytic Neoplasms",
    query: "Histiocytic Neoplasms",
    aliases: [],
    conflicts: [],
  },
  {
    id: "hodgkin-lymphoma",
    label: "Hodgkin Lymphoma",
    sourceLabel: "Hodgkin Lymphoma",
    query: "Hodgkin Lymphoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "kaposi-sarcoma",
    label: "Kaposi Sarcoma",
    sourceLabel: "Kaposi Sarcoma",
    query: "Kaposi Sarcoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "kidney-cancer",
    label: "Kidney Cancer",
    sourceLabel: "Kidney Cancer",
    query: "Kidney Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "melanoma-cutaneous",
    label: "Melanoma: Cutaneous",
    sourceLabel: "Melanoma: Cutaneous",
    query: "cutaneous melanoma",
    aliases: ["cutaneous melanoma", "skin melanoma", "melanoma of the skin", "malignant melanoma"],
    conflicts: ["uveal melanoma", "ocular melanoma", "choroidal melanoma", "mucosal melanoma"],
  },
  {
    id: "melanoma-uveal",
    label: "Melanoma: Uveal",
    sourceLabel: "Melanoma: Uveal",
    query: "uveal melanoma",
    aliases: ["uveal melanoma", "ocular melanoma", "choroidal melanoma", "intraocular melanoma"],
    conflicts: ["cutaneous melanoma", "skin melanoma"],
  },
  {
    id: "merkel-cell-carcinoma",
    label: "Merkel Cell Carcinoma",
    sourceLabel: "Merkel Cell Carcinoma",
    query: "Merkel Cell Carcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "mesothelioma-peritoneal",
    label: "Mesothelioma: Peritoneal",
    sourceLabel: "Mesothelioma: Peritoneal",
    query: "Mesothelioma Peritoneal",
    aliases: [],
    conflicts: [],
  },
  {
    id: "mesothelioma-pleural",
    label: "Mesothelioma: Pleural",
    sourceLabel: "Mesothelioma: Pleural",
    query: "Mesothelioma Pleural",
    aliases: [],
    conflicts: [],
  },
  {
    id: "multiple-myeloma",
    label: "Multiple Myeloma",
    sourceLabel: "Multiple Myeloma",
    query: "Multiple Myeloma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "myelodysplastic-syndromes",
    label: "Myelodysplastic Syndromes",
    sourceLabel: "Myelodysplastic Syndromes",
    query: "Myelodysplastic Syndromes",
    aliases: [],
    conflicts: [],
  },
  {
    id: "myeloid-lymphoid-neoplasms-with-eosinophilia-and-tyrosine-kinase-gene-fusions",
    label: "Myeloid/Lymphoid Neoplasms with Eosinophilia and Tyrosine Kinase Gene Fusions",
    sourceLabel: "Myeloid/Lymphoid Neoplasms with Eosinophilia and Tyrosine Kinase Gene Fusions",
    query: "Myeloid Lymphoid Neoplasms with Eosinophilia and Tyrosine Kinase Gene Fusions",
    aliases: [],
    conflicts: [],
  },
  {
    id: "myeloproliferative-neoplasms",
    label: "Myeloproliferative Neoplasms",
    sourceLabel: "Myeloproliferative Neoplasms",
    query: "Myeloproliferative Neoplasms",
    aliases: [],
    conflicts: [],
  },
  {
    id: "neuroblastoma",
    label: "Neuroblastoma",
    sourceLabel: "Neuroblastoma",
    query: "Neuroblastoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "neuroendocrine-and-adrenal-tumors",
    label: "Neuroendocrine Tumors (NET)",
    sourceLabel: "Neuroendocrine and Adrenal Tumors",
    query: "neuroendocrine tumor",
    aliases: ["neuroendocrine tumor", "neuroendocrine tumors", "neuroendocrine tumour", "neuroendocrine tumours", "neuroendocrine neoplasm", "neuroendocrine neoplasms", "neuroendocrine carcinoma", "NET", "GEP-NET", "carcinoid", "carcinoid tumor", "pancreatic neuroendocrine tumor", "pNET"],
    conflicts: ["adrenocortical carcinoma", "pheochromocytoma"],
    sourceCategory: "Neuroendocrine and Adrenal Tumors",
  },
  {
    id: "non-small-cell-lung-cancer",
    label: "Non-Small Cell Lung Cancer",
    sourceLabel: "Non-Small Cell Lung Cancer",
    query: "non small cell lung cancer",
    aliases: ["non small cell lung cancer", "non-small cell lung cancer", "non-small-cell lung cancer", "NSCLC", "nonsmall cell lung cancer"],
    conflicts: [],
  },
  {
    id: "occult-primary",
    label: "Occult Primary",
    sourceLabel: "Occult Primary",
    query: "Occult Primary",
    aliases: [],
    conflicts: [],
  },
  {
    id: "ovarian-cancer-fallopian-tube-cancer-primary-peritoneal-cancer",
    label: "Ovarian Cancer/Fallopian Tube Cancer/Primary Peritoneal Cancer",
    sourceLabel: "Ovarian Cancer/Fallopian Tube Cancer/Primary Peritoneal Cancer",
    query: "Ovarian Cancer Fallopian Tube Cancer Primary Peritoneal Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "pancreatic-adenocarcinoma",
    label: "Pancreatic Adenocarcinoma",
    sourceLabel: "Pancreatic Adenocarcinoma",
    query: "Pancreatic Adenocarcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "pediatric-acute-lymphoblastic-leukemia",
    label: "Pediatric Acute Lymphoblastic Leukemia",
    sourceLabel: "Pediatric Acute Lymphoblastic Leukemia",
    query: "Pediatric Acute Lymphoblastic Leukemia",
    aliases: [],
    conflicts: [],
  },
  {
    id: "pediatric-aggressive-mature-b-cell-lymphomas",
    label: "Pediatric Aggressive Mature B-Cell Lymphomas",
    sourceLabel: "Pediatric Aggressive Mature B-Cell Lymphomas",
    query: "Pediatric Aggressive Mature B-Cell Lymphomas",
    aliases: [],
    conflicts: [],
  },
  {
    id: "pediatric-central-nervous-system-cancers",
    label: "Pediatric Central Nervous System Cancers",
    sourceLabel: "Pediatric Central Nervous System Cancers",
    query: "Pediatric Central Nervous System Cancers",
    aliases: [],
    conflicts: [],
  },
  {
    id: "pediatric-hodgkin-lymphoma",
    label: "Pediatric Hodgkin Lymphoma",
    sourceLabel: "Pediatric Hodgkin Lymphoma",
    query: "Pediatric Hodgkin Lymphoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "pediatric-soft-tissue-sarcoma",
    label: "Pediatric Soft Tissue Sarcoma",
    sourceLabel: "Pediatric Soft Tissue Sarcoma",
    query: "Pediatric Soft Tissue Sarcoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "penile-cancer",
    label: "Penile Cancer",
    sourceLabel: "Penile Cancer",
    query: "Penile Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "prostate-cancer",
    label: "Prostate Cancer",
    sourceLabel: "Prostate Cancer",
    query: "Prostate Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "rectal-cancer",
    label: "Rectal Cancer",
    sourceLabel: "Rectal Cancer",
    query: "Rectal Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "small-bowel-adenocarcinoma",
    label: "Small Bowel Adenocarcinoma",
    sourceLabel: "Small Bowel Adenocarcinoma",
    query: "Small Bowel Adenocarcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "small-cell-lung-cancer",
    label: "Small Cell Lung Cancer",
    sourceLabel: "Small Cell Lung Cancer",
    query: "small cell lung cancer",
    aliases: ["small cell lung cancer", "small cell lung carcinoma", "SCLC", "small-cell lung cancer"],
    conflicts: ["non-small cell lung cancer", "non small cell lung cancer", "NSCLC", "nonsmall cell lung cancer"],
  },
  {
    id: "soft-tissue-sarcoma",
    label: "Soft Tissue Sarcoma",
    sourceLabel: "Soft Tissue Sarcoma",
    query: "Soft Tissue Sarcoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "squamous-cell-skin-cancer",
    label: "Squamous Cell Skin Cancer",
    sourceLabel: "Squamous Cell Skin Cancer",
    query: "Squamous Cell Skin Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "systemic-light-chain-amyloidosis",
    label: "Systemic Light Chain Amyloidosis",
    sourceLabel: "Systemic Light Chain Amyloidosis",
    query: "Systemic Light Chain Amyloidosis",
    aliases: [],
    conflicts: [],
  },
  {
    id: "systemic-mastocytosis",
    label: "Systemic Mastocytosis",
    sourceLabel: "Systemic Mastocytosis",
    query: "Systemic Mastocytosis",
    aliases: [],
    conflicts: [],
  },
  {
    id: "t-cell-lymphomas",
    label: "T-Cell Lymphomas",
    sourceLabel: "T-Cell Lymphomas",
    query: "T-Cell Lymphomas",
    aliases: [],
    conflicts: [],
  },
  {
    id: "testicular-cancer",
    label: "Testicular Cancer",
    sourceLabel: "Testicular Cancer",
    query: "Testicular Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "thymomas-and-thymic-carcinomas",
    label: "Thymomas and Thymic Carcinomas",
    sourceLabel: "Thymomas and Thymic Carcinomas",
    query: "Thymomas and Thymic Carcinomas",
    aliases: [],
    conflicts: [],
  },
  {
    id: "thyroid-carcinoma",
    label: "Thyroid Carcinoma",
    sourceLabel: "Thyroid Carcinoma",
    query: "Thyroid Carcinoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "uterine-neoplasms",
    label: "Uterine Neoplasms",
    sourceLabel: "Uterine Neoplasms",
    query: "Uterine Neoplasms",
    aliases: [],
    conflicts: [],
  },
  {
    id: "vaginal-cancer",
    label: "Vaginal Cancer",
    sourceLabel: "Vaginal Cancer",
    query: "Vaginal Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "vulvar-cancer",
    label: "Vulvar Cancer",
    sourceLabel: "Vulvar Cancer",
    query: "Vulvar Cancer",
    aliases: [],
    conflicts: [],
  },
  {
    id: "waldenstrom-macroglobulinemia-lymphoplasmacytic-lymphoma",
    label: "Waldenström Macroglobulinemia/Lymphoplasmacytic Lymphoma",
    sourceLabel: "Waldenström Macroglobulinemia/Lymphoplasmacytic Lymphoma",
    query: "Waldenström Macroglobulinemia Lymphoplasmacytic Lymphoma",
    aliases: [],
    conflicts: [],
  },
  {
    id: "wilms-tumor-nephroblastoma",
    label: "Wilms Tumor (Nephroblastoma)",
    sourceLabel: "Wilms Tumor (Nephroblastoma)",
    query: "Wilms Tumor (Nephroblastoma)",
    aliases: [],
    conflicts: [],
  },
] as const;

/** The demonstration's primary cancer, used by the NET treatment selector. */
export const NET_CANCER_ID = "neuroendocrine-and-adrenal-tumors";

export function findCancer(id: string): CancerEntry | undefined {
  return CANCERS.find((c) => c.id === id);
}
